### ISSUE TITLE
A question about a helper script I'm writing

### ISSUE THREAD

**Issue by m455** [trash-town/homepage#14]
Hey friends, I just finished writing a small little script for generating an HTML page that lists all of the folks on trash.town.

would we prefer to have it print the HTML to stdout, or to a file?

**Comment by archangelic** [comment]
Maybe have it able to do either? I need to set up some scripts to automatically create the gemini and gopher sites from our html.

**Comment by m455** [comment]
sounds good! I'll add like... `--stdout` and `--html <path>` flags or something

**Comment by m455** [comment]
@archangelic hell yeah, it's all done! https://github.com/trash-town/folks/

ideally, we would add a <a href="/folks.html">folks</a> to the nav bars on all pages and this script would populate that page!

**Comment by archangelic** [comment]
NEARLY 2 YEARS LATER, I finally generated this page! https://trash.town/folks.html I will add it to what I do when I add new users!
