### ISSUE TITLE
navigation bar idea

### ISSUE THREAD

**Issue by m455** [trash-town/homepage#5]
what if we had the twitter and mastodon links inside of a "contact" link or something at the top, and then a "donate" link containing a link to the patreon?

that way, if people don't know what mastodon is (people know what twitter is lol), they will know it is some medium of communication.

the same with patreon.

basically replacing names of services with words describing how they function.

so something like:

`home <> news <> signup <> wiki <> contact <> donate`

let me know what you think! i don't think there is anything wrong with what we have, it's just another option i'm throwing out there :dancer:  :D

**Comment by l0010o0001l** [comment]
Yes, I like that. Have all the socials on one link, and the donate can have a link to the Patreon, and the stuff about donating hardware

**Comment by archangelic** [comment]
Yes, I like that. Have all the socials on one link, and the donate can have a link to the Patreon, and the stuff about donating hardware

**Comment by m455** [comment]
yesss good call on the hardware being on the donation page!

**Comment by m455** [comment]
i've got a PR ready for this here: https://github.com/trash-town/homepage/pull/12

gonna close this discussion now
