### ISSUE TITLE
The removal of Weechat and Irssi

### ISSUE THREAD

**Issue by m455** [trash-town/homepage#7]
Hey trash mammals,

we were talking about going more async with trash.town, especially since it's such a cute, little, low-powered computer.

if this is the case, do we want to install weechat and irssi? I think it was me who installed them in the first place out of excitement. 

if we do, maybe we should remove them from the wiki too.

**Comment by archangelic** [comment]
We can leave the clients on there. That’s not an issue. Especially since we do have an irc presence just not an internal server.

**Comment by archangelic** [comment]
Unless we feel like we should encourage internal only async comms when sshed into trash.town?

**Comment by m455** [comment]
> Unless we feel like we should encourage internal only async comms when sshed into trash.town?

Maybe we can see what happens when more users join? because, i'm cool either way

**Comment by m455** [comment]
i'll close this for now, since it isn't a issue right now :)
